### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by dashmage**

### CODE REVIEW

**Review by Pjack — CHANGES_REQUESTED** [review]
Some codes has overlap with this #27. We can merge this after that.

**Review by sudeephb — APPROVED** [review]
LGTM

**Comment by dashmage** [comment]
Removed the bionic changes from this PR and rebased from main branch.

**Review by sudeephb — APPROVED** [review]
LGTM

**Review by Pjack — APPROVED** [review]

**Pull request merged**
